### ISSUE TITLE
Wrong address of $ARB token

### ISSUE THREAD

**Issue by 0xHumban** [whonion/ArbitrumMultiClaimerAndSender#2]
I don't know if it's a issue but the address of $ARB shown in readme is not the official address.

I think the good address is : 0x912ce59144191c1204e64559fe8253a0e49e6548

You can see all official address here : https://docs.arbitrum.foundation/deployment-addresses

**Comment by whonion** [comment]
The address you are referring to is a proxy contract.
But the token itself is at the address:
https://arbiscan.io/address/0x912CE59144191C1204E64559FE8253a0e49E6548#writeProxyContract
That is, you can also specify the one in the documentation, the transaction will in any case come to the one specified in REAME.md

**Comment by 0xHumban** [comment]
yes i miss read, it why i closed the issue sorry for the fud
